import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { HiOutlineArrowLeft, HiOutlineSearch, HiOutlineX } from 'react-icons/hi';
import FilterDropdown from '../components/FilterDropdown';
import TablePagination from '../components/TablePagination';
import useOrders from '../context/useOrders';
import { formatMoney } from '../data/mockOrders';
import { getShippingPartners, SHIPPING_PARTNER_SYNC_SLICE } from '../data/shippingPartners';
import { DELIVERY_STATUSES, DELIVERY_SYNC_SLICE, deliveryStatusKey, deliveryStatusLabel, getDeliveries, receiveReturnedStock, updateDelivery } from '../data/deliveries';
import { subscribeToAdminSlice } from '../sync/adminSync';
import './QuanLyGiaoHang.css';

const LIST_ROUTE = '/admin/don-hang/quan-ly-giao-hang';
const PARTNER_ROUTE = '/admin/khach-hang-doi-tac/doi-tac-van-chuyen';
const PAGE_SIZE = 10;
const STATUS_OPTIONS = ['Tất cả trạng thái', ...DELIVERY_STATUSES.map(([, label]) => label)];
const normalize = (value = '') => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D').toLowerCase();
const formatDate = (value) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const moneyOrZero = (value) => Number(value) ? formatMoney(value) : '0đ';

export default function QuanLyGiaoHang() {
  const { deliveryId } = useParams();
  const navigate = useNavigate();
  const { orders, patchOrder } = useOrders();
  const [deliveries, setDeliveries] = useState(() => getDeliveries());
  const [partners, setPartners] = useState(() => getShippingPartners());

  useEffect(() => subscribeToAdminSlice(DELIVERY_SYNC_SLICE, () => setDeliveries(getDeliveries())), []);
  useEffect(() => subscribeToAdminSlice(SHIPPING_PARTNER_SYNC_SLICE, () => setPartners(getShippingPartners())), []);

  const records = useMemo(() => deliveries.map((delivery) => ({ ...delivery, order: orders.find((order) => order.id === delivery.maDonHang), partner: partners.find((partner) => partner.id === delivery.doiTacId) })), [deliveries, orders, partners]);
  const persist = (id, changes, action) => {
    const updated = updateDelivery(id, changes, action);
    setDeliveries(getDeliveries());
    if (changes.trangThaiGiao) {
      const source = records.find((item) => item.id === id);
      patchOrder(source?.maDonHang, { delivery: deliveryStatusLabel(changes.trangThaiGiao) }, { title: 'CẬP NHẬT GIAO HÀNG', description: `Phiếu ${id}: ${deliveryStatusLabel(changes.trangThaiGiao)}`, tone: changes.trangThaiGiao === 'giao_thanh_cong' ? 'green' : 'black' });
    }
    return updated;
  };
  if (deliveryId) return <DeliveryDetail record={records.find((item) => item.id === deliveryId)} partners={partners} navigate={navigate} persist={persist} />;
  return <DeliveryList records={records} navigate={navigate} />;
}

function DeliveryList({ records, navigate }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(STATUS_OPTIONS[0]); const [partnerName, setPartnerName] = useState('Tất cả đối tác'); const [page, setPage] = useState(1);
  const partnerOptions = useMemo(() => ['Tất cả đối tác', ...Array.from(new Set(records.map((record) => record.partner?.tenDoiTac).filter(Boolean)))], [records]);
  const filtered = useMemo(() => records.filter((record) => {
    const term = normalize(query.trim()); const haystack = [record.id, record.maVanDon, record.maDonHang, record.order?.recipient?.name, record.order?.recipient?.phone];
    return (!term || haystack.some((value) => normalize(value || '').includes(term))) && (status === STATUS_OPTIONS[0] || record.trangThaiGiao === deliveryStatusKey(status)) && (partnerName === 'Tất cả đối tác' || record.partner?.tenDoiTac === partnerName);
  }), [records, query, status, partnerName]);
  const safePage = Math.min(page, Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)));
  const visible = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  const counts = DELIVERY_STATUSES.map(([key, label]) => [key, label, filtered.filter((item) => item.trangThaiGiao === key).length]);
  return <section className="delivery-page delivery-list-page">
    <header className="delivery-page-head"><div><nav>ADMIN <span>/</span> <strong>GIAO HÀNG</strong></nav><h1>GIAO HÀNG</h1></div></header>
    <div className="delivery-toolbar"><label className="delivery-search"><HiOutlineSearch /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Tìm mã phiếu / mã vận đơn / mã đơn / tên hoặc SĐT người nhận..." /></label><FilterDropdown className="delivery-filter" options={STATUS_OPTIONS} value={status} onSelect={(value) => { setStatus(value); setPage(1); }} /><FilterDropdown className="delivery-filter" options={partnerOptions} value={partnerName} onSelect={(value) => { setPartnerName(value); setPage(1); }} /><strong className="delivery-count">{filtered.length} PHIẾU</strong></div>
    <div className="delivery-table-scroll"><table className="delivery-table"><thead><tr><th>MÃ PHIẾU</th><th>MÃ VẬN ĐƠN</th><th>MÃ ĐƠN HÀNG</th><th>ĐÓNG GÓI</th><th>TRẠNG THÁI GIAO</th><th>ĐỐI TÁC</th><th>COD</th><th>PHÍ ĐỐI TÁC</th><th>NGƯỜI NHẬN</th><th>SĐT</th><th>ĐỊA CHỈ</th><th>CẬP NHẬT</th><th>THAO TÁC</th></tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td><b>{record.id}</b></td><td className={!record.maVanDon ? 'delivery-muted' : ''}>{record.maVanDon || '—'}</td><td><button className="delivery-link" onClick={() => navigate(`/admin/don-hang/danh-sach-don-hang/${record.maDonHang}`)}>{record.maDonHang}</button></td><td><ReadOnlyBadge value={record.order?.packing || '—'} /></td><td><DeliveryBadge status={record.trangThaiGiao} /></td><td><button className="delivery-partner-link" onClick={() => navigate(PARTNER_ROUTE, { state: { partnerId: record.doiTacId } })}><b>{record.partner?.tenDoiTac || '—'}</b><small>{record.doiTacId}</small></button></td><td className={record.cod ? 'delivery-money-red' : 'delivery-muted'}>{record.cod ? formatMoney(record.cod) : 'Không thu'}</td><td className="delivery-money">{moneyOrZero(record.phiDoiTac)}</td><td>{record.order?.recipient?.name || '—'}</td><td>{record.order?.recipient?.phone || '—'}</td><td className="delivery-address">{record.order?.recipient?.address || '—'}</td><td>{formatDate(record.updatedAt)}</td><td><button className="delivery-detail-btn" onClick={() => navigate(`${LIST_ROUTE}/${record.id}`)}>XEM CHI TIẾT</button></td></tr>)}{!visible.length && <tr><td colSpan="13" className="delivery-empty">Không tìm thấy phiếu giao hàng phù hợp.</td></tr>}</tbody></table></div>
    <footer className="delivery-list-footer"><div className="delivery-status-counts">{counts.map(([key, label, count]) => <span key={key}>{label.toLocaleUpperCase('vi')} <b>{count}</b></span>)}</div><TablePagination totalItems={filtered.length} pageSize={PAGE_SIZE} currentPage={safePage} onPageChange={setPage} idPrefix="delivery" showSummary={false} /></footer>
  </section>;
}

function DeliveryDetail({ record, partners, navigate, persist }) {
  const [modal, setModal] = useState('');
  if (!record?.order) return <section className="delivery-page delivery-not-found"><h1>KHÔNG TÌM THẤY PHIẾU GIAO HÀNG</h1><button onClick={() => navigate(LIST_ROUTE)}>QUAY LẠI</button></section>;
  const order = record.order; const merchandise = order.products.reduce((sum, product) => sum + Number(product.subtotal || 0), 0); const locked = record.trangThaiGiao !== 'cho_giao';
  const transition = (nextStatus) => { persist(record.id, { trangThaiGiao: nextStatus }, 'status-changed'); setModal(''); };
  const confirmReturn = (returnInfo) => { const stockAdjustments = receiveReturnedStock(record, returnInfo); persist(record.id, { trangThaiGiao: 'da_hoan_hang', returnInfo: { ...returnInfo, stockAdjustments, receivedAt: new Date().toISOString() } }, 'return-received'); setModal(''); };
  return <section className="delivery-page delivery-detail-page"><header className="delivery-detail-head"><nav>ADMIN <span>/</span> GIAO HÀNG <span>/</span> <strong>CHI TIẾT PHIẾU GIAO HÀNG</strong></nav><button className="delivery-back" onClick={() => navigate(LIST_ROUTE)}><HiOutlineArrowLeft /> QUAY LẠI</button></header><div className="delivery-detail-inner"><StatusStrip order={order} delivery={record.trangThaiGiao} /><div className="delivery-detail-grid"><div className="delivery-detail-main">
    <Panel title="THÔNG TIN GIAO HÀNG" tools={!locked ? <button className="delivery-small-btn" onClick={() => setModal('edit')}>CHỈNH SỬA THÔNG TIN VẬN ĐƠN</button> : <span className="delivery-lock-note">HÀNG ĐÃ ĐƯỢC BÀN GIAO — THÔNG TIN VẬN ĐƠN ĐÃ ĐƯỢC KHÓA</span>}><dl className="delivery-info-grid"><Info label="MÃ PHIẾU GIAO HÀNG">{record.id}</Info><Info label="MÃ VẬN ĐƠN">{record.maVanDon || '—'}</Info><Info label="TRẠNG THÁI">{deliveryStatusLabel(record.trangThaiGiao)}</Info><Info label="NGÀY TẠO">{formatDate(record.updatedAt)}</Info><Info label="NGƯỜI NHẬN">{order.recipient.name}</Info><Info label="SỐ ĐIỆN THOẠI">{order.recipient.phone || '—'}</Info><Info wide label="ĐỊA CHỈ GIAO HÀNG">{order.recipient.address}</Info><Info wide label="MÃ ĐƠN HÀNG"><button className="delivery-link" onClick={() => navigate(`/admin/don-hang/danh-sach-don-hang/${order.id}`)}>{order.id}</button></Info></dl></Panel>
    <Panel title="CHI TIẾT HÀNG HÓA"><div className="delivery-items-wrap"><table className="delivery-items"><thead><tr><th>SẢN PHẨM</th><th>PHIÊN BẢN</th><th>ĐƠN GIÁ</th><th>SL</th><th>THÀNH TIỀN</th></tr></thead><tbody>{order.products.map((item) => <tr key={item.barcode}><td>{item.name}</td><td><b>{item.variant}</b></td><td>{formatMoney(item.unitPrice)}</td><td>{item.quantity}</td><td className="delivery-money-red">{formatMoney(item.subtotal)}</td></tr>)}</tbody></table></div><dl className="delivery-summary"><Info label="Tổng tiền hàng">{formatMoney(merchandise)}</Info><Info label="Chiết khấu">{order.discount ? formatMoney(order.discount) : '—'}</Info><Info label="VAT">—</Info><Info label="Phí giao hàng">{moneyOrZero(order.shippingFee)}</Info><div className="delivery-total"><dt>KHÁCH PHẢI TRẢ</dt><dd>{formatMoney(order.total)}</dd></div></dl></Panel>
  </div><aside className="delivery-detail-side"><Panel title="THÔNG TIN VẬN CHUYỂN"><dl className="delivery-side-info"><Info label="ĐỐI TÁC VẬN CHUYỂN"><button className="delivery-link" onClick={() => navigate(PARTNER_ROUTE, { state: { partnerId: record.doiTacId } })}>{record.partner?.tenDoiTac || '—'}</button></Info><Info label="MÃ ĐỐI TÁC">{record.doiTacId}</Info><Info label="MÃ VẬN ĐƠN">{record.maVanDon || '—'}</Info><Info label="TIỀN THU HỘ COD">{moneyOrZero(record.cod)}</Info><Info label="PHÍ TRẢ ĐỐI TÁC">{moneyOrZero(record.phiDoiTac)}</Info></dl></Panel><ActionPanel status={record.trangThaiGiao} onAction={(action) => { if (action === 'received') transition('da_nhan_hang'); else if (action === 'start') transition('dang_giao'); else setModal(action); }} /></aside></div></div>
  {modal === 'edit' && <EditShipmentModal record={record} partners={partners} close={() => setModal('')} save={(changes) => { persist(record.id, changes, 'shipment-updated'); setModal(''); }} />}{modal === 'success' && <SuccessModal cod={record.cod} close={() => setModal('')} confirm={() => transition('giao_thanh_cong')} />}{modal === 'failure' && <FailureModal close={() => setModal('')} confirm={() => transition('cho_hoan_hang')} />}{modal === 'return' && <ReturnModal items={order.products} close={() => setModal('')} confirm={confirmReturn} />}</section>;
}

function StatusStrip({ order, delivery }) { const values = [['ĐƠN HÀNG', order.status], ['THANH TOÁN', order.payment], ['ĐÓNG GÓI', order.packing], ['XUẤT KHO', order.warehouse], ['GIAO HÀNG', deliveryStatusLabel(delivery)]]; return <div className="delivery-status-strip">{values.map(([label, value], index) => <div key={label}><span>{label}</span>{index === 4 ? <DeliveryBadge status={delivery} /> : <ReadOnlyBadge value={value} />}</div>)}</div>; }
function Panel({ title, tools, children }) { return <section className="delivery-panel"><header><h2><i />{title}</h2>{tools}</header>{children}</section>; }
function Info({ label, wide, children }) { return <div className={wide ? 'wide' : ''}><dt>{label}</dt><dd>{children}</dd></div>; }
function DeliveryBadge({ status }) { return <span className={`delivery-badge delivery-badge--${status}`}>{deliveryStatusLabel(status).toLocaleUpperCase('vi')}</span>; }
function ReadOnlyBadge({ value }) { const tone = /Đã|Hoàn thành/.test(value) ? 'green' : /Hủy/.test(value) ? 'red' : /Chưa/.test(value) ? 'orange' : 'gray'; return <span className={`delivery-readonly-badge is-${tone}`}>{String(value).toLocaleUpperCase('vi')}</span>; }
function ActionPanel({ status, onAction }) { let content; if (status === 'cho_giao') content = <button className="delivery-action black" onClick={() => onAction('received')}>XÁC NHẬN ĐỐI TÁC ĐÃ NHẬN HÀNG</button>; else if (status === 'da_nhan_hang') content = <button className="delivery-action black" onClick={() => onAction('start')}>BẮT ĐẦU GIAO HÀNG</button>; else if (status === 'dang_giao') content = <><button className="delivery-action success" onClick={() => onAction('success')}>GIAO THÀNH CÔNG</button><button className="delivery-action danger" onClick={() => onAction('failure')}>GIAO THẤT BẠI</button></>; else if (status === 'cho_hoan_hang') content = <><span className="delivery-action waiting">ĐANG CHỜ ĐỐI TÁC HOÀN HÀNG VỀ CỬA HÀNG</span><button className="delivery-action return" onClick={() => onAction('return')}>XÁC NHẬN ĐÃ NHẬN HÀNG HOÀN</button></>; else content = <p className="delivery-terminal">PHIẾU ĐÃ HOÀN TẤT — KHÔNG CÓ THAO TÁC BỔ SUNG</p>; return <section className="delivery-actions-panel"><h2><i />THAO TÁC</h2><div>{content}</div></section>; }

function ModalShell({ title, tone = 'neutral', close, children, footer, wide = false }) { return <div className="delivery-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className={`delivery-modal delivery-modal--${tone} ${wide ? 'is-wide' : ''}`} role="dialog" aria-modal="true"><header><h2><i />{title}</h2><button onClick={close} aria-label="Đóng"><HiOutlineX /></button></header><div className="delivery-modal-body">{children}</div><footer>{footer}</footer></section></div>; }
function ModalButton({ children, variant = 'back', disabled, onClick }) { return <button type="button" className={`delivery-modal-button is-${variant}`} disabled={disabled} onClick={onClick}>{children}</button>; }
function EditShipmentModal({ record, partners, close, save }) { const [tracking, setTracking] = useState(record.maVanDon || ''); const [partnerId, setPartnerId] = useState(record.doiTacId || ''); const [fee, setFee] = useState(String(record.phiDoiTac || 0)); const activePartners = partners.filter((partner) => partner.trangThai === 'hoat_dong'); const valid = Boolean(partnerId) && fee !== '' && Number(fee) >= 0; return <ModalShell title="CHỈNH SỬA THÔNG TIN VẬN ĐƠN" close={close} footer={<><ModalButton onClick={close}>QUAY LẠI</ModalButton><ModalButton variant="black" disabled={!valid} onClick={() => save({ maVanDon: tracking.trim(), doiTacId: partnerId, phiDoiTac: Number(fee) })}>LƯU THAY ĐỔI</ModalButton></>}><label className="delivery-field"><span>MÃ VẬN ĐƠN</span><input value={tracking} onChange={(event) => setTracking(event.target.value)} placeholder="Nhập mã vận đơn..." /></label><label className="delivery-field"><span>ĐỐI TÁC VẬN CHUYỂN *</span><select value={partnerId} onChange={(event) => setPartnerId(event.target.value)}><option value="">Chọn đối tác</option>{activePartners.map((partner) => <option key={partner.id} value={partner.id}>{partner.tenDoiTac} ({partner.id})</option>)}</select></label><label className="delivery-field"><span>PHÍ TRẢ ĐỐI TÁC *</span><input type="text" inputMode="numeric" value={fee === '' ? '' : new Intl.NumberFormat('vi-VN').format(Number(fee))} onChange={(event) => setFee(event.target.value.replace(/\D/g, ''))} onBlur={() => setFee(String(Math.max(0, Number(fee) || 0)))} /><b className="currency-suffix">đ</b></label></ModalShell>; }
function SuccessModal({ cod, close, confirm }) { const [checked, setChecked] = useState(false); return <ModalShell title="XÁC NHẬN GIAO THÀNH CÔNG" tone="success" close={close} footer={<><ModalButton onClick={close}>QUAY LẠI</ModalButton><ModalButton variant="success" disabled={!checked} onClick={confirm}>XÁC NHẬN ĐÃ GIAO</ModalButton></>}><div className="delivery-cod"><span>TIỀN COD CẦN THU</span><strong>{formatMoney(cod)}</strong></div><label className="delivery-checkbox"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} /> Xác nhận shipper đã thu đủ tiền COD từ khách</label></ModalShell>; }
function FailureModal({ close, confirm }) { return <ModalShell title="XÁC NHẬN GIAO HÀNG THẤT BẠI?" tone="danger" close={close} footer={<><ModalButton onClick={close}>QUAY LẠI</ModalButton><ModalButton variant="danger" onClick={confirm}>XÁC NHẬN THẤT BẠI</ModalButton></>}><p className="delivery-warning">Hàng sẽ chuyển sang trạng thái <b>CHỜ HOÀN VỀ CỬA HÀNG.</b></p></ModalShell>; }
function ReturnModal({ items, close, confirm }) { const [rows, setRows] = useState(() => items.map((item) => ({ barcode: item.barcode, name: item.name, variant: item.variant, exported: item.quantity, nguyenVen: item.quantity, loi: 0, error: '' }))); const [reason, setReason] = useState(''); const [note, setNote] = useState(''); const changeQty = (index, field, raw) => setRows((current) => current.map((row, rowIndex) => { if (rowIndex !== index) return row; const value = Math.max(0, Math.floor(Number(raw) || 0)); const other = field === 'nguyenVen' ? Number(row.loi) : Number(row.nguyenVen); if (value + other > row.exported) return { ...row, error: `Tổng số lượng không được vượt quá ${row.exported}.` }; return { ...row, [field]: value, error: '' }; })); const valid = Boolean(reason.trim()) && rows.every((row) => !row.error && Number(row.nguyenVen) + Number(row.loi) <= row.exported); const cleanRows = () => rows.map(({ error: _error, ...row }) => row); return <ModalShell wide title="XÁC NHẬN HÀNG HOÀN VỀ KHO" tone="return" close={close} footer={<><ModalButton onClick={close}>QUAY LẠI</ModalButton><ModalButton variant="return" disabled={!valid} onClick={() => confirm({ items: cleanRows(), lyDoTra: reason.trim(), ghiChu: note.trim() })}>XÁC NHẬN ĐÃ NHẬN HÀNG HOÀN</ModalButton></>}><p className="delivery-warning">Hàng hoàn sẽ được nhập vào kho mặc định của cửa hàng. Không chọn kho khác.</p><h3>HÀNG NHẬN VỀ</h3>{rows.map((row, index) => <div className="delivery-return-row" key={row.barcode}><strong>{row.name}</strong><small>{row.variant} · Số lượng đã xuất: {row.exported}</small><div><label>SỐ LƯỢNG NGUYÊN VẸN<input type="number" min="0" max={row.exported} value={row.nguyenVen} onChange={(event) => changeQty(index, 'nguyenVen', event.target.value)} /></label><label>SỐ LƯỢNG LỖI<input type="number" min="0" max={row.exported} value={row.loi} onChange={(event) => changeQty(index, 'loi', event.target.value)} /></label></div>{row.error && <em>{row.error}</em>}</div>)}<label className="delivery-field"><span>LÝ DO TRẢ *</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ví dụ: Khách không nhận, đối tác đã hoàn đủ..." /></label><label className="delivery-field"><span>GHI CHÚ</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Tình trạng hàng khi nhận lại..." /></label></ModalShell>; }
